name: microservices-platform

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-offerly}
      POSTGRES_USER: ${POSTGRES_USER:-offerly}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-offerly-local-password}
    ports:
      - "55432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:4.3.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9094:9094"
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "11025:1025"
      - "18025:8025"
    restart: unless-stopped

  auth-service:
    build:
      context: ./services/auth-service
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-local-development-secret-change-me-now}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      AUTH_NAME: ${AUTH_NAME:-Admin}
      AUTH_EMAIL: ${AUTH_EMAIL:-admin@example.com}
      AUTH_PASSWORD: ${AUTH_PASSWORD:-admin123}
      KAFKA_BROKERS: kafka:9092
      SWAGGER_ENABLED: "true"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB:-offerly}
      DATABASE_USER: ${POSTGRES_USER:-offerly}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-offerly-local-password}
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_FROM: ${SMTP_FROM:-Offerly <no-reply@offerly.local>}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:3001}
    ports:
      - "3000:3000"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    restart: unless-stopped

volumes:
  kafka-data:
  postgres-data:
