import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityManager, Repository } from 'typeorm';
import { WorkflowService } from '../workflow/workflow.service';
import { WorkflowStage } from '../workflow/entities/workflow-stage.entity';
import { questionItems } from '../utils/preparation.utils';
import { GeneratePreparationDto } from './dto/preparation.dto';
import { StagePreparationData } from './entities/stage-preparation.entity';
import { PreparationContextService } from './services/preparation-context.service';
import { PreparationStrategyFactory } from './strategies/preparation-strategy.factory';
@Injectable()
export class PreparationService {
  /** Stages with an AI call in progress in this instance. */
  private readonly generating = new Set<string>();
  constructor(
    @InjectRepository(StagePreparationData)
    private readonly preparations: Repository<StagePreparationData>,
    private readonly workflows: WorkflowService,
    private readonly context: PreparationContextService,
    private readonly factory: PreparationStrategyFactory,
    private readonly dataSource: DataSource
  ) {}
  async get(
    userId: string,
    workflowId: string,
    stageId: string
  ): Promise<StagePreparationData> {
    await this.workflows.requireStage(userId, workflowId, stageId);
    const preparation = await this.preparations.findOneBy({ stageId });
    if (!preparation)
      throw new NotFoundException('Stage preparation not found');
    return preparation;
  }

  async generate(
    userId: string,
    workflowId: string,
    stageId: string,
    input: GeneratePreparationDto,
    authorization: string
  ): Promise<StagePreparationData> {
    const workflow = await this.workflows.requireWorkflow(userId, workflowId);
    const stage = await this.workflows.stages.findOne({
      where: { id: stageId, workflowId },
      relations: { stageType: true }
    });
    if (!stage) throw new NotFoundException('Workflow stage not found');
    const stageType = stage.stageType;
    const instructions = input.instructions?.trim() ?? '';
    if (stageType.ownerUserId && !instructions)
      throw new BadRequestException(
        'Describe what to expect at this personal stage'
      );
    const type = this.factory.resolveType(stageType, input.type);
    if (
      this.generating.has(stageId) ||
      (await this.preparations.existsBy({ stageId }))
    )
      throw new ConflictException(
        'Preparation already exists or is being generated; delete it explicitly before regenerating'
      );
    this.generating.add(stageId);
    try {
      const context = await this.context.load(
        workflow.vacancyId,
        authorization
      );
      const data = await this.factory.getStrategy(type).generate({
        ...context,
        stage: {
          name: stage.name,
          category: stage.category,
          code: stageType.code
        },
        instructions: instructions || `Prepare for ${stage.name}`
      });
      return await this.dataSource.transaction(async (manager) => {
        await this.lockStage(manager, workflowId, stageId);
        if (await manager.existsBy(StagePreparationData, { stageId }))
          throw new ConflictException(
            'Preparation was generated by another request'
          );
        return manager.save(
          StagePreparationData,
          manager.create(StagePreparationData, {
            stageId,
            data,
            instructions: instructions || null
          })
        );
      });
    } finally {
      this.generating.delete(stageId);
    }
  }
  async answer(
    userId: string,
    workflowId: string,
    stageId: string,
    questionId: string,
    userAnswer: string
  ): Promise<StagePreparationData> {
    await this.workflows.requireStage(userId, workflowId, stageId);
    return this.dataSource.transaction(async (manager) => {
      await this.lockStage(manager, workflowId, stageId);
      const preparation = await manager.findOneBy(StagePreparationData, {
        stageId
      });
      if (!preparation)
        throw new NotFoundException('Stage preparation not found');
      const question = questionItems(preparation.data).find(
        (item) => item.id === questionId
      );
      if (!question)
        throw new NotFoundException('Preparation question not found');
      question.userAnswer = userAnswer;
      return manager.save(StagePreparationData, preparation);
    });
  }
  async remove(
    userId: string,
    workflowId: string,
    stageId: string
  ): Promise<void> {
    await this.workflows.requireStage(userId, workflowId, stageId);
    await this.dataSource.transaction(async (manager) => {
      await this.lockStage(manager, workflowId, stageId);
      const result = await manager.delete(StagePreparationData, { stageId });
      if (!result.affected)
        throw new NotFoundException('Stage preparation not found');
    });
  }
  private async lockStage(
    manager: EntityManager,
    workflowId: string,
    stageId: string
  ): Promise<void> {
    const stage = await manager.findOne(WorkflowStage, {
      where: { id: stageId, workflowId },
      lock: { mode: 'pessimistic_write' }
    });
    if (!stage) throw new NotFoundException('Workflow stage not found');
  }
}
